config/routes.rb
Cricket::Application.routes.draw do
    resources :scores

  root :to => "scores#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/batting.rb
class Batting < ActiveRecord::Base
  attr_accessible :team_id, :score_id, :innings, :name, :runs, :balls , :ones, :twos, :threes, :fours, :sixes, :status,
   :bowler, :strikerate
  belongs_to :score
  belongs_to :team

    before_save do
		self.runs = (1*self.ones)+(2*self.twos)+(3*self.threes)+(4*self.fours)+(6*self.sixes)
		self.strikerate = ((self.runs / self.balls.to_f)*100).round(2)
	end
end

app/models/bowler.rb
class Bowler < ActiveRecord::Base
  attr_accessible :team_id, :score_id, :innings, :name, :runs, :overs, :avg, :wides, :noball, :maidens, :wkts
  belongs_to :score
  belongs_to :team


  	before_save do
		self.avg = (self.runs/self.overs).to_f.round(2)
	end 
end

app/models/score.rb
class Score < ActiveRecord::Base
	attr_accessible :name, :team1, :team2, :team1score, :team2score, :toss, :venue, :date, :guest1, :photo1, :guest2, :photo2, :guest3, :photo3, :guest4, :photo4, :guest5, :photo5

	has_many :battings
	has_many :bowlers

	has_attached_file :photo1, :styles => { :small => "150x150>" },
	              :url  => "/assets/scores/:id/:style/:basename.:extension",
	              :path => ":rails_root/public/assets/scores/:id/:style/:basename.:extension"

	
	validates_attachment_size :photo1, :less_than => 5.megabytes
	validates_attachment_content_type :photo1, :content_type => ['image/jpeg', 'image/png']


	has_attached_file :photo2, :styles => { :small => "150x150>" },
	              :url  => "/assets/scores/:id/:style/:basename.:extension",
	              :path => ":rails_root/public/assets/scores/:id/:style/:basename.:extension"

	
	validates_attachment_size :photo2, :less_than => 5.megabytes
	validates_attachment_content_type :photo2, :content_type => ['image/jpeg', 'image/png']


	has_attached_file :photo3, :styles => { :small => "150x150>" },
	              :url  => "/assets/scores/:id/:style/:basename.:extension",
	              :path => ":rails_root/public/assets/scores/:id/:style/:basename.:extension"

	
	validates_attachment_size :photo3, :less_than => 5.megabytes
	validates_attachment_content_type :photo3, :content_type => ['image/jpeg', 'image/png']


	has_attached_file :photo4, :styles => { :small => "150x150>" },
	              :url  => "/assets/scores/:id/:style/:basename.:extension",
	              :path => ":rails_root/public/assets/scores/:id/:style/:basename.:extension"

	
	validates_attachment_size :photo4, :less_than => 5.megabytes
	validates_attachment_content_type :photo4, :content_type => ['image/jpeg', 'image/png']


	has_attached_file :photo5, :styles => { :small => "150x150>" },
	              :url  => "/assets/scores/:id/:style/:basename.:extension",
	              :path => ":rails_root/public/assets/scores/:id/:style/:basename.:extension"

	
	validates_attachment_size :photo5, :less_than => 5.megabytes
	validates_attachment_content_type :photo5, :content_type => ['image/jpeg', 'image/png']



end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name
  has_many :battings
  has_many :bowlers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>MJ-MPL</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
  	<div class="col-lg-13">
     	<a href="/"><img src="/assets/Bhanu.jpg" width="100%" id="banner"></a>
	</div>
	<div class="col-lg-13">
		<div id="scroller">
			<span id="static-text">MPL Updates</span>
			<div class="scrollingtext">
				<% score_count = 0 %>
				<% scores = Score.all %>
				<% scores.sort.each do |score| %>
					<% if score.date == Date.today %>
						<% score_count += 1 %>
						<span class="review">
							<span class="message">
								<a href="/scores/<%= score.id %>">Today's Match-<%= score_count %> - <%= score.name %> (<%= score.team1 %> vs  <%= score.team2 %>)
								</a>
							</span> -
							<span class="forename"><%= score.venue %></span> 
						</span>
					<% end %>
				<% end %>
				<% if score_count == 0 %>
					<% scores.sort.each do |score| %>
						<% score_count += 1 %>
						<span class="review">
							<span class="message">
								<a href="/scores/<%= score.id %>">Match-<%= score_count %> - <%= score.name %> (<%= score.team1 %> vs  <%= score.team2 %>)
								</a>
							</span> -
						<span class="forename"><%= score.venue %></span> 
					<% end %>	
				<% end %>
			</div>
		</div>
	</div>
	<br>
	<div id="container">
		<%= yield %>
	</div>
</body>
</html>



<style type="text/css">
@media (max-width: 767px){
	#banner{
		height: 80px;
	}
}

a{
	text-decoration: none !important;
}

a:hover
{
	background: transparent;
	color: #232323;
}
body{
	background-image: url('/assets/background.png');
}
</style>

app/views/scores/_batting.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Runs</th>
        <th>Balls</th>
        <th>1's</th>
        <th>2's</th>
        <th>3's</th>
        <th>Fours</th>
        <th>Sixes</th>
        <th>Status</th>
        <th>Strike Rate</th>
        <th>Bowler</th>
      </tr>
    </thead>
    <tbody>
      <% @battings1.reverse.each do |bat| %>
        <tr>
          <td><%= bat.name %></td>
          <td><%= bat.runs %></td>
          <td><%= bat.balls %></td>
          <td><%= bat.ones %></td>
          <td><%= bat.twos %></td>
          <td><%= bat.threes %></td>
          <td><%= bat.fours %></td>
          <td><%= bat.sixes %></td>
          <td>
            <% if bat.status == true %>
              Out
            <% else %>
              Bat
            <% end %>
          </td>
          <td><%= bat.strikerate %></td>
          <td><%= bat.bowler %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  
<hr>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Bowler</th>
        <th>Runs</th>
        <th>Overs</th>
        <th>Wides</th>
        <th>Noballs</th>
        <th>Maidens</th>
        <th>Wickets</th>
        <th>Econ</th>
      </tr>
    </thead>
    <tbody>
      <% @bowlings1.reverse.each do |bowl| %>
        <tr>
          <td><%= bowl.name %></td>
          <td><%= bowl.runs %></td>
          <td><%= bowl.overs %></td>
          <td><%= bowl.wides %></td>
          <td><%= bowl.noball %></td>
          <td><%= bowl.maidens %></td>
          <td><%= bowl.wkts %></td>
          <td><%= bowl.avg %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  

app/views/scores/_bowling.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Runs</th>
        <th>Balls</th>
        <th>1's</th>
        <th>2's</th>
        <th>3's</th>
        <th>Fours</th>
        <th>Sixes</th>
        <th>Status</th>
        <th>Strike Rate</th>
        <th>Bowler</th>
      </tr>
    </thead>
    <tbody>
      <% @battings2.reverse.each do |bat| %>
        <tr>
          <td><%= bat.name %></td>
          <td><%= bat.runs %></td>
          <td><%= bat.balls %></td>
          <td><%= bat.ones %></td>
          <td><%= bat.twos %></td>
          <td><%= bat.threes %></td>
          <td><%= bat.fours %></td>
          <td><%= bat.sixes %></td>
          <td>
            <% if bat.status == true %>
              Out
            <% else %>
              Bat
            <% end %>
          </td>
          <td><%= bat.strikerate %></td>
          <td><%= bat.bowler %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  
<hr>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Bowler</th>
        <th>Runs</th>
        <th>Overs</th>
        <th>Wides</th>
        <th>Noballs</th>
        <th>Maidens</th>
        <th>Wickets</th>
        <th>Econ</th>
      </tr>
    </thead>
    <tbody>
      <% @bowlings2.reverse.each do |bowl| %>
        <tr>
          <td><%= bowl.name %></td>
          <td><%= bowl.runs %></td>
          <td><%= bowl.overs %></td>
          <td><%= bowl.wides %></td>
          <td><%= bowl.noball %></td>
          <td><%= bowl.maidens %></td>
          <td><%= bowl.wkts %></td>
          <td><%= bowl.avg %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team1 %><br />
    <%= f.text_field :team1 %>
  </div>
  <div class="field">
    <%= f.label :team2 %><br />
    <%= f.text_field :team2 %>
  </div>
  <div class="field">
    <%= f.label :toss %><br />
    <%= f.text_field :toss %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/_profile.html.erb
<ul  class="row">
  <% @battings.each do |bat| %>
    <li class="col-lg-4" id="profile">
      <img src="/assets/player_profile.jpeg" class="col-lg-4">
      <%= bat.name %><br>
      <%= bat.runs %>(<%= pluralize(bat.balls,"ball") %>)<br>
      <%= bat.team.name %>
    </li>
  <% end %>
</ul>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <td>S.No</td>
        <td>Match</td>
        <td>Team-1</td>
        <td>Team-2</td>
        <td>Venue</td>
        <td>Score Card</td>
      </tr>
    </thead>
    <tbody>
      <% @scores.sort.each do |score| %>
        <tr>
          <td><%= score.id %></td>
          <td><%= score.name %></td>
          <td><%= Team.find(score.team1).name %></td>
          <td><%= Team.find(score.team2).name %></td>
          <td><%= score.venue %></td>
          <td><%= link_to "Scorecard", score %></td>
        </tr>  
      <% end %>
    </tbody>
  </table>
</div>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
  <!-- score and innings dynamic -->
  <% @battings1 = Batting.find_all_by_score_id_and_innings(@score.id,1) %>
  <% @bowlings1 = Bowler.find_all_by_score_id_and_innings(@score.id,1) %>
  <% @battings2 = Batting.find_all_by_score_id_and_innings(@score.id,2) %>
  <% @bowlings2 = Bowler.find_all_by_score_id_and_innings(@score.id,2) %>
  <% @battings = @battings1 + @battings2 %>

  <!-- end -->

  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <div class="col-lg-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">
              <%= Team.find(@score.team1).name %> <i>Vs</i> <%= Team.find(@score.team2).name %>
            </h3>
          </div>
          <div class="panel-body">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
              <li class="active">
                <a href="#innings1" data-toggle="tab">Ininngs 1</a>
              </li>
              <li>
                <a href="#innings2" data-toggle="tab">Ininngs 2</a>
              </li>
              <li>
                <a href="#innings3" data-toggle="tab">Profile</a>
              </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <div class="tab-pane active" id="innings1">
                  <%= render "batting" %>
              </div>
              <div class="tab-pane" id="innings2">
                <%= render "bowling" %>
              </div>
              <div class="tab-pane" id="innings3">
                <%= render "profile" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
      <div class="list-group">
        <b  class="list-group-item active">Match</b>
  
        <b  class="list-group-item"><%= Team.find(@score.team1).name %> <i>VS</i> <%= Team.find(@score.team2).name %></b>
        <b class="list-group-item"><%= @score.toss %></b>
  
      </div>
      <div class="list-group">
        <b href="#" class="list-group-item active">Venue</b>
        <b href="#" class="list-group-item"><%= @score.venue %></b>
      </div>
       <div class="list-group">
        <b href="#" class="list-group-item active">Score</b>
        <b href="#" class="list-group-item"><%= Team.find(@score.team1).name %>:<%= @score.team1score %></b>
        <b href ="#" class="list-group-item"><%= Team.find(@score.team2).name %>:<%= @score.team2score %></b>
      </div>

      <div id="carousel-example-generic" class="carousel slide list-group" data-ride="carousel">
       
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        </ol>
       
        <!-- Slider Content (Wrapper for slides )-->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag @score.photo1.url, :style => "height:150px;width:320px;" %> 
            <div class="carousel-caption">
              <%= @score.guest1 %>
            </div>
          </div>
          <div class="item">
            <%= image_tag @score.photo2.url, :style => "height:150px;width:320px;" %> 
            <div class="carousel-caption">
              <%= @score.guest2 %>
            </div>
          </div>
          <div class="item">
            <%= image_tag @score.photo3.url, :style => "height:150px;width:320px;" %> 
            <div class="carousel-caption">
              <%= @score.guest3 %>
            </div>
          </div>
          <div class="item">
            <%= image_tag @score.photo4.url, :style => "height:150px;width:320px;" %> 
            <div class="carousel-caption">
              <%= @score.guest4 %>
            </div>
          </div>
          <div class="item">
            <%= image_tag @score.photo5.url, :style => "height:150px;width:320px;" %> 
            <div class="carousel-caption">
              <%= @score.guest5 %>
            </div>
          </div>
        </div>
       
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-arrow-back-16.png" align="middle">
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-arrow-forward-16.png">
        </a>
      </div>
    </div><!--/span-->
  </div>


<style type="text/css">
ul{
  list-style-type: none;
}
#profile{
  padding: 1em;
}
</style>